steps:
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      npm install
      npm run build  # Este paso compilará tu proyecto NestJS

# Este paso asegura que el código fuente sea desplegado sin Docker
images:
- 'gcr.io/$PROJECT_ID/backend-api-verco'
