steps:
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      npm install
      npm run build  # o 'npm run start:prod' si prefieres compilar y ejecutar
images:
- 'gcr.io/$PROJECT_ID/backend-api-verco'
