steps:
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      npm install
      npm run build
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/backend-api-verco'
    - '.'
images:
- 'gcr.io/$PROJECT_ID/backend-api-verco'
